### ISSUE TITLE
Scanner verabschiedet sich nach 1143 scan starts

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/Version-Scanner#1]
Nach dem gestrigen Scan "Rundumschlag" wurden lediglich 1143 von 2896 Scans gestartet.

Folgende Beobachtungen:

1. Gegen 15:25Z wurde der letzte Scan gestartet.
2. Danach erscheinen einige Stack Traces im Log
3. Die Ergebnisse von 91 der gestarteten Scans sind nicht in der DB aufgetaucht
4. 55 domains sind doppelt und mehrfach gescannt worden

Logdatei liegt hier vor.

**Comment by Lednerb** [comment]
Mittlerweile behoben per 8e4d22f045ec9e6f1518e0991294507f5fa218b3
