### ISSUE TITLE
Projektübergreifend einheitlicher Scanner-Name

### ISSUE THREAD

**Issue by Lednerb** [SIWECOS/Version-Scanner#10]
Momentan haben wir ein kleines Namenskonvention-Problem.

Der CMS-Versionsscanner hat zwei verschiedene Bezeichnungen:

1. Version-Scanner:

- GitHub: SIWECOS/Version-Scanner
- DockerHub: siwecos/version-scanner
- docker-compose-scanners: version-scanner (an Repo orientiert)

2. CMSVersion-Scanner:

- Translations-Repo: CMSVERSION
- Innerhalb des Scanners als `name` bei Response: CMSVERSION

----------------------------------------------

Wir sollten das auf eine einheitliche Bezeichnung runterbrechen.

Ich verstehe, dass wir hier eigentlich CMS-Versionen scannen, der Scanner daher CMSVERSION heißen sollte.

Da die Repos und entsprechenden Abhängigkeiten jedoch alle bereits auf `version-scanner` (ohne CMS) konfiguriert sind und wir im SIWECOS-Namen bereits Content-Management-Systeme haben, würde ich gerne den `name` auf `VERSION` ändern und im Translations-Repo dementsprechend die Anpassung haben, dass die generierte Übersetzungsdatei dementsprechend `VERSION.php` heißt.

Bitte kurzes Feedback, damit wir das schnell erledigen können.

**Comment by SniperSister** [comment]
Fine for me
