### ISSUE TITLE
Kundenanfrage

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/Version-Scanner#13]
Diese Anfrage kam herein:

> seit 17.07.2019 fragen Sie täglich mit Ihrem "SIWECOS Version Scanner"
> Dokumente von meinem Web-Server ab, die nicht existieren. Das geschah
> bisher über 3240 mal. Es sind zwar "nur" 80 Anfragen pro Nacht (ca. um
> 04:10), doch sollte ein derartiges Prüfen auf ein aktuelles CMS alle
> Woche oder gar Monat völlig ausreichen. Auch wäre eine Einstellung oder
> Erkennung sehr sinnvoll, dass kein CMS genutzt wird. Ich registriere
> jeden Versuch eines "Hacks" und diese werden per Protokolle und E-Mails
> dokumentiert. Daher ist mir wichtig Ihnen mein Aufwand mitzuteilen, der
> unnötig zum "Freischalten" und Aufräumen entsteht. Vielleicht finden
> Sie einen Kompromiss für solche Betreiber wie mich. Vielen Dank und
> trotz meiner (hoffentlich positiven) Kritik weiterhin viele gute Ideen
> und noch bessere Umsetzungen! Ich bin froh seit langer Zeit von Ihrem
> kostenfreien Service zu profitieren.

Kann dem Manne geholfen werden?

**Comment by Lednerb** [comment]
Wird in BLA behandelt.
