### ISSUE TITLE
Log-Ausgabe begrenzen / einzelne Requests nur im Debug Modus

### ISSUE THREAD

**Issue by Lednerb** [SIWECOS/Version-Scanner#15]
Bitte wie folgt die Log-Ausgabe begrenzen:

Momentan wird jeder einzelne Request geloggt.
Diese Ausgaben werden prinzipiell nicht benötigt um machen eigentlich nur in einer Debug-Umgebung Sinn.

Daher bitte das Log-Level auf `debug` stellen.

**Comment by SniperSister** [comment]
Done
