### ISSUE TITLE
Initialer Check, ob Seite erreichbar fehlt

### ISSUE THREAD

**Issue by Lednerb** [SIWECOS/Version-Scanner#19]
Folgendes Szenario:

Ein Scan zu einer URL wird gestartet. die komplett nicht erreichbar ist, bspw.: `https://does-not-even-exist.com`

Der Scanner prüft momentan nicht die Haupt-URL, sondern beginnt direkt mit dem Scan.
Am Ende gibt es folgendes Resultat:

```
{
   "name":"VERSION",
   "version":"1.0.0",
   "hasError":false,
   "errorMessage":null,
   "score":100,
   "tests":[
      {
         "name":"CMSVERSION",
         "errorMessage":null,
         "hasError":false,
         "score":100,
         "scoreType":"info",
         "testDetails":[
            {
               "translationStringId":"CMS_CANT_DETECT_CMS"
            }
         ]
      }
   ]
}
```

Bitte Initialen Check einbauen und erwartungsgemäß mit einem `hasError: true` sowie einer `errorMessage` Antworten, die besagt, dass die Seite nicht erreichbar ist.

**Comment by SniperSister** [comment]
Wird der Case nicht von der API abgefangen?

**Comment by Lednerb** [comment]
Durch die BLA indirekt ja, da wir Freescans nicht mehr mit `VERSION` machen und vorher die Verifizierung abgeschlossen werden muss.

Sollte der Scanner aber einzeln genutzt werden oder nur mit der CA, dann wird dies benötigt.
