### ISSUE TITLE
Version Scanner in Staging steigt bei meiner Domain aus

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/Version-Scanner#22]
In Production meldet es korrekt eine veraltete Joomla Version. In Staging gibt's einen "internen Fehler".

<img width="670" alt="image" src="https://user-images.githubusercontent.com/725404/68027311-4dbb2780-fcb2-11e9-891b-35c68c00b0a4.png">

**Comment by Lednerb** [comment]
Lag offenbar am Docker Netzwerk auf der Scanner Maschine in `staging`.

Erhalte nun das gleiche Ergebnis auch in staging.

**Comment by Skeeve** [comment]
Heute Nacht:

<img width="666" alt="image" src="https://user-images.githubusercontent.com/725404/68067096-7d197500-fd42-11e9-9254-51e6ff8cd6ec.png">

**Comment by Lednerb** [comment]
Ein erneuter Scan (ohne Änderung an den Servern, etc.) lief erfolgreich und lieferte wieder den erwarteten Wert.

Wahrscheinlich antwortete der Server deiner Seite in der Nacht nicht oder nicht schnell genug, sodass der Timeout des `VERSION`-Scanners griff.

**Comment by Lednerb** [comment]
Analyse: von 28 Scans heute Nacht in `staging` mit dem `VERSION`-Scanner gibt es insgesamt 4 `Could not connect`-Fehler.

Weitere hierzu im Slack.

**Comment by Skeeve** [comment]
In Prodiction, 9 Minuten nach Staging.

<img width="710" alt="image" src="https://user-images.githubusercontent.com/725404/68067914-5feaa380-fd4e-11e9-8deb-bfcac532242f.png">

**Comment by Skeeve** [comment]
Heute Nacht ist er wieder ausgetsiegen. Ein manueller Scan wiederum hat funktioniert.

**Comment by Skeeve** [comment]
Regelmäßig steigt eer in staging aus, in Production nicht. Heute Nacht wieder. Diesmeal war der Scan in staging um 2:01 in Production um 2:10.

**Comment by Skeeve** [comment]
P.S. Einen relevanten Unterschied zwischen staging und prod kann ich in keiner Datei feststellen.

In Prod gibt es allerdings 2 Dateien mehr:

```
./storage/framework/views/4582e0f2e6dcf957a44e90a8f6a6f071cd28b720.php
./storage/framework/views/aa25a1173c3517ee7cf3dfac53bf68d1d31dae3a.php
```

Ansonsten unterscheiden sich noch

```
./storage/signatures/candidates.json
./storage/signatures/signatures.json
```

Aber ich nehme nicht an, dass dies von Bedeutung ist

**Comment by Lednerb** [comment]
> Aber ich nehme nicht an, dass dies von Bedeutung ist

Korrekt, am Scanner liegt es nicht.

**Comment by Skeeve** [comment]
Angehängt die Log-Auszüge von meinem Server.

Staging unternimmt anscheinend gar keinen Versuch, die CMS Version zu testen. Seit dem 30. sehe ich in den Logdateien nachts um 2 Staging "anklopfen", aber den eigentlichen Scan sieht man nicht.

Anders dagegen in production.

**Comment by Skeeve** [comment]
Nach Analyse durch @SniperSister habe ich beschlossen: Wir ignorieren das, auch wenn es nicht nur bei meiner Domain so ist, und hoffen, dass die Produktionsmaschine schnell genug die Antworten bekommt um nicht zu meinen, dass die Gegenseite nicht antwortet.
