### ISSUE TITLE
Doppelter Code?

### ISSUE THREAD

**Issue by Skeeve** [SIWECOS/Version-Scanner#3]
Ich gebe zu: Viel Ahnung von Laravel und PHP habe ich nicht, aber ist das hier

https://github.com/SIWECOS/Version-Scanner/blob/08309d9e3acfc47ddd05f6cdfe7a55a832e34d8c/app/Http/Controllers/ApiController.php#L18

nicht eine Codedopplung von `VersionScanJob::handle`? Wäre es nicht sinnvoll, das aufzurufen?

**Comment by SniperSister** [comment]
Ist es, das eine wird aber synchron ausgeführt und gibt einen Return wert, das andere läuft asynchron und macht einen callback. Lässt sich daher nicht zusammen fassen.
