### ISSUE TITLE
IDN-Domains [Umlaute] unterstützen

### ISSUE THREAD

**Issue by Lednerb** [SIWECOS/Version-Scanner#8]
Momentan werden keine Umlaut-Domains unterstützt.

Der Scanner muss hierfür eine entsprechende Konvertierung vornehmen.

Siehe bspw.:
https://github.com/SIWECOS/HSHS-DOMXSS-Scanner/blob/749bb513f312f94755706d9bc0dc72dfadfe48d1/app/HTTPResponse.php#L139-L160

Das Docker-Image unterstützt bereits die `idn_` Erweiterungen.

**Comment by SniperSister** [comment]
Fix ist gepushed, bitte prüfen :)

**Comment by Lednerb** [comment]
Fixed
